### ISSUE TITLE
Typescript Codegen Support

### ISSUE THREAD

**Issue by mattpocock** [lucydsl/liblucy#15]
Opening this issue to spawn a discussion about type-safety. Lucy offers a nice opportunity to increase TS type safety by statically analysing the machine. This is similar to, but much more reliable than, [xstate-codegen](https://github.com/mattpocock/xstate-codegen). `xstate-codegen` pulls out machines from JS/TS, which is fraught with issues. Lucy could statically analyse files, free of side effects, and create 100% perfect types every time.

What do perfect types look like? 

1. All actions/guards/services know what events caused them to fire.
2. `state.matches` can be made type safe.

Because Lucy compiles to `out.js` files, an accompanying `.d.ts` file would be appropriate. Users could also pass it generics, such as `TEvent` and `TContext`, similar to `xstate-codegen`.

Interested to hear your thoughts.

**Comment by mattpocock** [comment]
@matthewp More thoughts on this:

https://www.loom.com/share/24611881ff44467ca021f63e33f18599

**Comment by matthewp** [comment]
Hey @mattpocock I really like your ideas here! I agree about moving inline actions/guards into the named section. I'm on board with that. A JSON version seems interesting and relatively simple too. Would love to hear more about how that might be used (easier to integrate with a visualizer maybe?)

I've been on vacation so haven't been diving deeply into TS yet but should be able to respond more in the next few days. One thing I have a question about is what is the user experience of types in a non-JS language? Does the user need to first compile to .d.ts and import the JS file (as you would using the CLI)? Or can they import the .lucy file using one of the build tool plugins and still get types? If so how would TS know about the types in .lucy files? Is there some kind of protocol for this?

More thoughts to come later. Thanks so much for your interest in moving this forward!

**Comment by mattpocock** [comment]
@matthewp

> Does the user need to first compile to .d.ts and import the JS file?

No! You can actually strongly type the .lucy file directly. You can declare a specific module with an arbitrary file extension.

> Would love to hear more about how [a JSON version] might be used

Some of this is still TBD, but the possibilities are interesting. The visual builder will most likely use JSON as its 'source code' - i.e. editing an in-place JSON definition of a machine. Giving Lucy the ability to print that JSON into 'lucy' would be pretty cool - but one for the future.

**Comment by matthewp** [comment]
This part is still unclear to me: https://twitter.com/matthewcp/status/1390276561392308224

I want to make sure we figure this out as part of adding good TS support. I think most people are going to be using bundler plugins and importing .lucy files, so it doesn't help if the generated JS has good type definitions of the editor doesn't know about them.

**Comment by mattpocock** [comment]
> This part is still unclear to me

Could the bundler plugin print Typescript declaration files? Similar to `css-modules-typescript-loader`

**Comment by mattpocock** [comment]
@matthewp I've been wanting to learn VSCode Language Server stuff for a while - would this be a part of [lucy-vscode](https://github.com/matthewp/lucy-vscode)?

**Comment by matthewp** [comment]
To get support for types coming from bundler usage like: `import createTodoMachine from './todo.lucy'` I think that yeah, that likely is something that has to be done in a language server. Currently there isn't a language server at all for Lucy, it's just syntax highlighting. It would go in that project though.

The Svelte language server has to do something similar: https://github.com/sveltejs/language-tools

**Comment by mattpocock** [comment]
@matthewp Got any other good resources around this? I'll dive into Svelte/Vue to see how they manage.

**Comment by matthewp** [comment]
No, I'm pretty new to it myself. I did find a few YouTube videos when I was learning about this, so there is some resources out there.

**Comment by matthewp** [comment]
Just an update here, with 0.3.0 out and the module signature in a better place, this will likely be the major thing done for 0.4.0.

I'm approaching it from VSCode first perspective, so depending what is needed there will determine what the initial approach will be here.

**Comment by matthewp** [comment]
Status here is that I've been investigating this issue more and did a spike on a language service for VSCode. At this point I think the best course of action is a TypeScript Language Service plugin (https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin). This will allow you to get Lucy support through the existing TypeScript language service in your editor.

My plan is to do a quick spike on that, and then the next step will likely be declaration file generation from the CLI compiler.

**Comment by matthewp** [comment]
The TypeScript plugin will be here: https://github.com/lucydsl/typescript-plugin

**Comment by matthewp** [comment]
I've gotten far enough on the typescript plugin to conclude that compiling to `.d.ts` will work for vscode integration. 🎉. https://github.com/lucydsl/typescript-plugin/pull/1

So the next step is putting a pause on the development of that to add `.d.ts` output to the compiler/cli. As I work on this piece I'll likely ping people here to see if they like the output that I come up with.

**Comment by matthewp** [comment]
I'm leaning towards the CLI including dts files by default if you use `--out-file` or `--out-dir`. Let me know if anyone feels differently.

**Comment by mattpocock** [comment]
@matthewp Fabulous

**Comment by matthewp** [comment]
Just a little update, I'm now able to produce this:

```ts
import { EventObject, StateMachine } from 'xstate';

interface CreateMachineOptions<TContext, TEvent extends EventObject> {
  guards: {
    check: Guard<TContext, TEvent>;
  }
}

export default function<TContext, TEvent extends EventObject>(
  opts: CreateMachineOptions<TContext, TEvent>
): StateMachine<TContext, MachineSchema, TEvent>;
```

Next I'll tackle producing the StateSchema. Let me know if anyone sees something wrong with the above.

**Comment by mattpocock** [comment]
Very nice. My dream here is, similar to xstate-codegen, produce an output where the guard knows _exactly_ which event initiated it. This works by doing:

`Guard<TContext, Extract<TEvent, { type: 'THE_EVENT_THAT_CALLED_ME' | 'ANOTHER_POSSIBLE_EVENT' }>>`

This would take this from _pretty good_ to _better than anything else XState can do currently_

**Comment by matthewp** [comment]
@mattpocock Is that valid today or are we talking about future features? Sorry, when it comes to this advanced TypeScript support and a bunch of nested type param stuff I am very much a novice. Is `Extract` a real thing? Is it builtin to TS or do I have to import it some how?

If this is possible now then, yeah, let's add it, we know the possible events after all.

**Comment by mattpocock** [comment]
@matthewp Yep, `Extract` is a native TS utility, valid today. Want to do a call about this and I can show you around the generics of `xstate-codegen`? We've solved much more complicated generics than this there and it works beautifully.

**Comment by matthewp** [comment]
If we want to say that a guard can be used with specific events, is this the way to do it?

```ts
interface CreateMachineOptions<TContext, TEvent extends EventObject> {
  guards: {
    check: Guard<
      TContext, 
      TEvent extends Extract<
        TEvent,
        { type: 'next' } | { type: 'go_back' }
       > ?
          Extract<
            TEvent,
            { type: 'next' } | { type: 'go_back' }
           > : 
          TEvent
    >;
  }
```

What I'm trying to say with the above is: the `check` guard will be used by both the `next` and `go_back` events. Is this the right way to express that?

**Comment by mattpocock** [comment]
@matthewp Yes! Looks good - something slightly more terse would be:
```ts
Extract<TEvent, { type: 'next' | 'go_back' }>
```

**Comment by matthewp** [comment]
Small update, I'm able to produce this now:

```ts
import { EventObject, StateMachine, Guard } from 'xstate';

type MachineEventNames = 'idle' | 'loading' | 'loaded' | 'homescreen';

type MachineKnownContextKeys = 'count' | 'todo';

interface CreateMachineOptions<TContext, TEvent extends EventObject> {
  guards: {
    check: Guard<
      TContext,
      TEvent extends Extract<TEvent, { type: 'next' }> ? Extract<TEvent, { type: 'next' }> : TEvent
    >
  }
}

export default function createMachine<TContext extends Record<MachineKnownContextKeys, any>, TEvent extends { type: MachineEventNames } = any>(options: CreateMachineOptions<TContext, TEvent>): StateMachine<TContext, any, TEvent>;
```

Just guards. Actions, Assign, Services, Delays, should follow fairly straightforward.

Notice this part: `StateMachine<TContext, any, TEvent>`. Second argument is `any` because we are not producing a state schema.

**Comment by mattpocock** [comment]
@matthewp Hell yes, great progress.

```ts
interface CreateMachineOptions<TContext, TEvent extends EventObject>
```

Should be:

```ts
interface CreateMachineOptions<TContext, TEvent extends { type: MachineEventNames }>
```

**Comment by matthewp** [comment]
@mattpocock Thanks, this is why my TS knowledge falls apart. I thought the fact that the `createMachine` definition extends that, that TEvent should already be the right thing when passed into CreateMachineOptions. Why do you have to keep extending the same thing?

**Comment by mattpocock** [comment]
It's kind of double protection. It means that if anyone uses `CreateMachineOptions` themselves independently (which we should probably allow them to do by exporting it), they'll be forced to use the correct `TEvent` type too

**Comment by mattpocock** [comment]
You are right though, if they never use `CreateMachineOptions` then your method will be strongly typed.

**Comment by matthewp** [comment]
Makes sense to export it. I'll make that change!

**Comment by mattpocock** [comment]
@matthewp Something will hopefully be landing in XState core that will make this easier to implement from your side:

https://github.com/statelyai/xstate/pull/2651

This gives you the ability to specify a generic along with the machine that powers up its type definitions - i.e. gives you the ability to specify which events cause which actions/services etc:

```ts
interface Meta {
  __generated: 1;
  eventsCausingServices: {
    myService: 'FOO';
  };
}
const machine = createMachine({
  types: {} as typeof Meta,
  invoke: {
    src: 'myService'
  }
}, {
  services: {
    myService: async (context, event) => {
      // event is typed to be { type: 'FOO' }
    }
  }
})
```

This should mean less wizardry needed from you to get this done.

**Comment by matthewp** [comment]
Oh very interesting, good to know! I've already implemented most of the generic wizardry so it's not an issue at this point, but as a possible refactor in the future its good to hear.

**Comment by matthewp** [comment]
I think I'm going to do a release with this turned on through a `--experimental-dts` flag. I think it's about ready to be tested out in the wild but am fairly certain there are bugs, wouldn't want people depending on this yet.

**Comment by mattpocock** [comment]
Epic

**Comment by matthewp** [comment]
I'm having some issues getting the wasm to build locally, so it might be until tomorrow before this is released.

**Comment by matthewp** [comment]
It's out! https://github.com/lucydsl/liblucy/releases/tag/v0.4.0
