### ISSUE TITLE
Add option for outputting to JSON

### ISSUE THREAD

**Issue by mattpocock** [lucydsl/liblucy#38]
This would be great for building tools with Lucy - for instance a browser-based visualiser.

**Comment by matthewp** [comment]
Is there a standard format for what this JSON looks like? Are there any existing tools that consume the JSON format?

**Comment by mattpocock** [comment]
@matthewp None - I'm imagining that for now, we'd copy the XState format (i.e. the first argument to createMachine) in JSON form.

**Comment by tonivj5** [comment]
if lucy exports a xstate machine, we could use its visualizer out-of-the-box, couldn't?

**Comment by mattpocock** [comment]
I'd prefer to output to JSON so that you wouldn't need an intermediate Babel transpilation step.
