### ISSUE TITLE
Nested states without nested machines

### ISSUE THREAD

**Issue by matthewp** [lucydsl/liblucy#53]
I'm thinking that having nested states by nesting a machine is kind of strange. It's like a machine but also is completely tied to the outer. Does it make sense to just have states directly inside of states instead?

**Comment by alexander-js** [comment]
I admit that the nested machine declarations tripped me up in the beginning. Ditching them would make the language even terser, too.

**Comment by matthewp** [comment]
Thanks! I think we're probably going to go in that direction.
