### ISSUE TITLE
Why not javascript?

### ISSUE THREAD

**Issue by thehappycheese** [lucydsl/liblucy#75]
Hi there, this project looks great with super exciting potential :D

I came straight to the github, keen to see juicy implementation details, only to find it written in C, a language that I am generally not good at and find hard to read (and not buildable on windows?) :( Nothing wrong with C of course... I am just curious though, why not typescript / PEGjs for the core? Is javascript really too slow for this?

**Comment by matthewp** [comment]
It's for performance. The `lucyc` command compiles large projects faster than Node.js starts up :)
